"""add more variable types

Revision ID: 0cce847bb91d
Revises: 47ed1fcc374f
Create Date: 2025-11-20 16:15:32.402085

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0cce847bb91d"
down_revision: str | None = "47ed1fcc374f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "source_codes_configs",
        sa.Column("sensitive", sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()),
    )
    op.add_column(
        "source_codes_configs",
        sa.Column("restricted", sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("source_codes_configs", "restricted")
    op.drop_column("source_codes_configs", "sensitive")
    # ### end Alembic commands ###
