"""add_iac_repos

Revision ID: 0d6f8aecf9b7
Revises: 73eab5aee8af
Create Date: 2026-10-09 14:44:40.401300

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0d6f8aecf9b7"
down_revision: str | None = "73eab5aee8af"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "iac_environment_configs",
        sa.Column("source_code_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("storage_id", sa.UUID(), nullable=True),
        sa.Column("state_path_template", sa.String(), nullable=False),
        sa.Column("regions", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("region_variable", sa.String(), nullable=True),
        sa.Column("tool_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_code_id"], ["source_codes.id"], name="fk_iac_environment_config_source_code_id", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["storage_id"], ["storages.id"], name="fk_iac_environment_config_storage_id"),
        sa.ForeignKeyConstraint(
            ["tool_id"], ["tools.id"], name="fk_iac_environment_config_tool_id", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_iac_environment_config_source_code_id_name",
        "iac_environment_configs",
        ["source_code_id", "name"],
        unique=True,
    )
    op.create_table(
        "iac_runs",
        sa.Column("source_code_id", sa.UUID(), nullable=False),
        sa.Column("module_path", sa.String(), nullable=False),
        sa.Column("environment_name", sa.String(), nullable=False),
        sa.Column("region", sa.String(), nullable=True),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("ref", sa.String(), nullable=True),
        sa.Column("sha", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "IN_PROGRESS",
                "DONE",
                "ERROR",
                "CANCELLED",
                "UNKNOWN",
                "APPROVAL_PENDING",
                "PENDING",
                "REJECTED",
                "READY",
                "ENABLED",
                "DISABLED",
                name="model_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("to_add", sa.Integer(), nullable=True),
        sa.Column("to_change", sa.Integer(), nullable=True),
        sa.Column("to_destroy", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_code_id"], ["source_codes.id"], name="fk_iac_run_source_code_id", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_iac_run_stack",
        "iac_runs",
        ["source_code_id", "module_path", "environment_name", "created_at"],
        unique=False,
    )
    op.create_table(
        "iac_environment_config_integrations",
        sa.Column("environment_config_id", sa.UUID(), nullable=False),
        sa.Column("integration_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["environment_config_id"], ["iac_environment_configs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["integration_id"], ["integrations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("environment_config_id", "integration_id"),
    )
    op.add_column("services", sa.Column("source_code_id", sa.UUID(), nullable=True))
    op.create_foreign_key("fk_service_source_code_id", "services", "source_codes", ["source_code_id"], ["id"])
    op.add_column(
        "source_codes", sa.Column("repository_type", sa.String(), server_default="module_library", nullable=False)
    )
    op.add_column("source_codes", sa.Column("iac_modules", sa.JSON(none_as_null=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("source_codes", "iac_modules")
    op.drop_column("source_codes", "repository_type")
    op.drop_constraint("fk_service_source_code_id", "services", type_="foreignkey")
    op.drop_column("services", "source_code_id")
    op.drop_table("iac_environment_config_integrations")
    op.drop_index("ix_iac_run_stack", table_name="iac_runs")
    op.drop_table("iac_runs")
    op.drop_index("ix_iac_environment_config_source_code_id_name", table_name="iac_environment_configs")
    op.drop_table("iac_environment_configs")
    # ### end Alembic commands ###
