"""add config to workflow step

Revision ID: 17b2fb67c776
Revises: 3890388593d8
Create Date: 2026-10-08 21:59:15.447764

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "17b2fb67c776"
down_revision: str | None = "3890388593d8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflow_steps", sa.Column("resolved_dependency_config", sa.JSON(), server_default="{}", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflow_steps", "resolved_dependency_config")
    # ### end Alembic commands ###
