"""add code snapshot

Revision ID: 1de126f86fe4
Revises: 68808bd7a046
Create Date: 2026-05-22 10:22:03.607727

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1de126f86fe4"
down_revision: str | None = "68808bd7a046"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("source_code_versions", sa.Column("code_snapshot", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("source_code_versions", "code_snapshot")
    # ### end Alembic commands ###
