"""add entity cron

Revision ID: 253a298cb86c
Revises: b7e41c9d2f08
Create Date: 2026-09-26 15:14:54.173197

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "253a298cb86c"
down_revision: str | None = "b7e41c9d2f08"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("service_owners")
    op.drop_index(op.f("ix_service_project_id_name"), table_name="services")
    op.drop_index(op.f("ix_services_name"), table_name="services")
    op.drop_table("services")
    op.add_column("tasks", sa.Column("cron", sa.String(), nullable=True))
    op.add_column("tasks", sa.Column("timezone", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "timezone")
    op.drop_column("tasks", "cron")
    op.create_table(
        "services",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("display_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("project_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("repository_url", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("labels", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("revision_number", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("created_by", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], name=op.f("services_created_by_fkey")),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], name=op.f("fk_service_project_id")),
        sa.PrimaryKeyConstraint("id", name=op.f("services_pkey")),
    )
    op.create_index(op.f("ix_services_name"), "services", ["name"], unique=False)
    op.create_index(op.f("ix_service_project_id_name"), "services", ["project_id", "name"], unique=True)
    op.create_table(
        "service_owners",
        sa.Column("service_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], name=op.f("service_owners_service_id_fkey")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("service_owners_user_id_fkey")),
        sa.PrimaryKeyConstraint("service_id", "user_id", name=op.f("service_owners_pkey")),
    )
    # ### end Alembic commands ###
