"""migrate types

Revision ID: 2a21f0adafc4
Revises: b7d24e3f9a11
Create Date: 2026-03-02 11:28:19.124388

"""

from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "2a21f0adafc4"
down_revision: str | None = "b7d24e3f9a11"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_favorites_user_component"), table_name="favorites")
    # Update 'runtime' values from 'opentofu' to 'tofu' in 'executors' table
    op.execute("UPDATE executors SET runtime='tofu' WHERE runtime='opentofu'")
    op.execute("UPDATE secrets SET secret_type='tofu' WHERE secret_type='opentofu'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_favorites_user_component"), "favorites", ["user_id", "component_type", "component_id"], unique=False
    )
    # Revert 'runtime' values from 'tofu' back to 'opentofu' in 'executors' table
    op.execute("UPDATE executors SET runtime='opentofu' WHERE runtime='tofu'")
    op.execute("UPDATE secrets SET secret_type='opentofu' WHERE secret_type='tofu'")
    # ### end Alembic commands ###
