"""add_iac_vars

Revision ID: 36cb2dc77093
Revises: 0d6f8aecf9b7
Create Date: 2026-10-09 15:09:33.972383

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "36cb2dc77093"
down_revision: str | None = "0d6f8aecf9b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("iac_environment_configs", sa.Column("variables", sa.JSON(none_as_null=True), nullable=True))
    op.add_column("iac_environment_configs", sa.Column("region_variables", sa.JSON(none_as_null=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("iac_environment_configs", "region_variables")
    op.drop_column("iac_environment_configs", "variables")
    # ### end Alembic commands ###
