"""fix

Revision ID: 3e31964a93d7
Revises: 32bfeac67778
Create Date: 2026-04-17 16:13:28.666844

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3e31964a93d7"
down_revision: str | None = "32bfeac67778"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blueprint_workflows",
        sa.Column("blueprint_id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["blueprint_id"], ["blueprints.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("blueprint_id", "workflow_id"),
    )
    op.drop_constraint(op.f("workflows_blueprint_id_fkey"), "workflows", type_="foreignkey")
    op.drop_column("workflows", "blueprint_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workflows", sa.Column("blueprint_id", sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(
        op.f("workflows_blueprint_id_fkey"), "workflows", "blueprints", ["blueprint_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_table("blueprint_workflows")
    # ### end Alembic commands ###
