"""init

Revision ID: 47ed1fcc374f
Revises:
Create Date: 2025-10-27 16:39:17.928706

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "47ed1fcc374f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "caches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("module", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.LargeBinary(), nullable=False),
        sa.Column("expire_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_caches_key"), "caches", ["key"], unique=False)
    op.create_index(op.f("ix_caches_module"), "caches", ["module"], unique=False)
    op.create_table(
        "logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("entity", sa.String(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("level", sa.String(), nullable=False),
        sa.Column("data", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("execution_start", sa.Integer(), nullable=False),
        sa.Column("expire_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trace_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_created_at", "logs", ["created_at"], unique=False, postgresql_using="btree")
    op.create_index("ix_entity_id", "logs", ["entity_id"], unique=False)
    op.create_index("ix_execution_start", "logs", ["execution_start"], unique=False)
    op.create_index("ix_expire_at", "logs", ["expire_at"], unique=False, postgresql_using="btree")
    op.create_index("ix_trace_id", "logs", ["trace_id"], unique=False)
    op.create_table(
        "revisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scheduler_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("type", sa.Enum("SQL", "BASH", name="type", native_enum=False), nullable=False),
        sa.Column("script", sa.String(), nullable=False),
        sa.Column("cron", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("identifier", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("deactivated", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_identifier_provider", "users", ["identifier", "provider"], unique=True)
    op.create_table(
        "workers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("host", sa.String(), nullable=False),
        sa.Column("host_metadata", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "auth_providers",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("auth_provider", sa.String(), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("filter_by_domain", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auth_providers_auth_provider"), "auth_providers", ["auth_provider"], unique=True)
    op.create_index(op.f("ix_auth_providers_name"), "auth_providers", ["name"], unique=True)
    op.create_table(
        "casbin_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ptype", sa.String(), nullable=False),
        sa.Column("v0", sa.String(), nullable=True),
        sa.Column("v1", sa.String(), nullable=True),
        sa.Column("v2", sa.String(), nullable=True),
        sa.Column("v3", sa.String(), nullable=True),
        sa.Column("v4", sa.String(), nullable=True),
        sa.Column("v5", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_casbin_rules_types", "casbin_rules", ["ptype", "v0", "v1", "v2", "v3", "v4", "v5"], unique=True)
    op.create_table(
        "feature_flags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("config_name", sa.String(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("config_name"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "integrations",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("integration_type", sa.String(), nullable=False),
        sa.Column("integration_provider", sa.String(), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "IN_PROGRESS",
                "DONE",
                "ERROR",
                "UNKNOWN",
                "APPROVAL_PENDING",
                "PENDING",
                "REJECTED",
                "READY",
                "ENABLED",
                "DISABLED",
                name="model_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_name_integration_type_integration_provider",
        "integrations",
        ["name", "integration_type", "integration_provider"],
        unique=True,
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("entity", sa.String(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column(
            "state",
            sa.Enum("PROVISION", "PROVISIONED", "DESTROY", "DESTROYED", name="model_state", native_enum=False),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "IN_PROGRESS",
                "DONE",
                "ERROR",
                "UNKNOWN",
                "APPROVAL_PENDING",
                "PENDING",
                "REJECTED",
                "READY",
                "ENABLED",
                "DISABLED",
                name="model_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("template", sa.String(), nullable=False),
        sa.Column("cloud_resource_types", sa.JSON(), nullable=False),
        sa.Column("abstract", sa.Boolean(), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "IN_PROGRESS",
                "DONE",
                "ERROR",
                "UNKNOWN",
                "APPROVAL_PENDING",
                "PENDING",
                "REJECTED",
                "READY",
                "ENABLED",
                "DISABLED",
                name="model_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_templates_name"), "templates", ["name"], unique=True)
    op.create_index(op.f("ix_templates_template"), "templates", ["template"], unique=True)
    op.create_table(
        "user_accounts_associations",
        sa.Column("primary_user_id", sa.UUID(), nullable=False),
        sa.Column("secondary_user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["primary_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["secondary_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("primary_user_id", "secondary_user_id"),
        sa.UniqueConstraint("secondary_user_id", name="uq_secondary_user_id"),
    )
    op.create_table(
        "source_codes",
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("source_code_url", sa.String(), nullable=False),
        sa.Column("source_code_provider", sa.String(), nullable=False),
        sa.Column("source_code_language", sa.String(), nullable=False),
        sa.Column("integration_id", sa.UUID(), nullable=True),
        sa.Column("git_tags", sa.JSON(), nullable=False),
        sa.Column("git_tag_messages", sa.JSON(), nullable=True),
        sa.Column("git_branches", sa.JSON(), nullable=False),
        sa.Column("git_branch_messages", sa.JSON(), nullable=True),
        sa.Column("git_folders_map", sa.JSON(), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "IN_PROGRESS",
                "DONE",
                "ERROR",
                "UNKNOWN",
                "APPROVAL_PENDING",
                "PENDING",
                "REJECTED",
                "READY",
                "ENABLED",
                "DISABLED",
                name="model_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["integration_id"],
            ["integrations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_source_codes_source_code_url"), "source_codes", ["source_code_url"], unique=True)
    op.create_table(
        "storages",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("storage_type", sa.String(), nullable=False),
        sa.Column("storage_provider", sa.String(), nullable=False),
        sa.Column("integration_id", sa.UUID(), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column(
            "state",
            sa.Enum("PROVISION", "PROVISIONED", "DESTROY", "DESTROYED", name="model_state", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "IN_PROGRESS",
                "DONE",
                "ERROR",
                "UNKNOWN",
                "APPROVAL_PENDING",
                "PENDING",
                "REJECTED",
                "READY",
                "ENABLED",
                "DISABLED",
                name="model_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["integration_id"],
            ["integrations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "template_links",
        sa.Column("parent_id", sa.UUID(), nullable=False),
        sa.Column("child_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["templates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["templates.id"],
        ),
        sa.PrimaryKeyConstraint("parent_id", "child_id"),
    )
    op.create_table(
        "workspaces",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("workspace_provider", sa.String(), nullable=False),
        sa.Column("integration_id", sa.UUID(), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "IN_PROGRESS",
                "DONE",
                "ERROR",
                "UNKNOWN",
                "APPROVAL_PENDING",
                "PENDING",
                "REJECTED",
                "READY",
                "ENABLED",
                "DISABLED",
                name="model_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["integration_id"],
            ["integrations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_name_integration_id", "workspaces", ["name", "integration_id"], unique=True)
    op.create_table(
        "source_code_versions",
        sa.Column("template_id", sa.UUID(), nullable=False),
        sa.Column("source_code_id", sa.UUID(), nullable=False),
        sa.Column("source_code_version", sa.String(), nullable=True),
        sa.Column("source_code_branch", sa.String(), nullable=True),
        sa.Column("source_code_folder", sa.String(), nullable=False),
        sa.Column("variables", sa.JSON(), nullable=False),
        sa.Column("outputs", sa.JSON(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "IN_PROGRESS",
                "DONE",
                "ERROR",
                "UNKNOWN",
                "APPROVAL_PENDING",
                "PENDING",
                "REJECTED",
                "READY",
                "ENABLED",
                "DISABLED",
                name="model_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["source_code_id"], ["source_codes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["template_id"], ["templates.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_source_code_version_branch_unique",
        "source_code_versions",
        ["source_code_id", "source_code_version", "source_code_folder"],
        unique=True,
    )
    op.create_index(
        "ix_source_code_version_version_unique",
        "source_code_versions",
        ["source_code_id", "source_code_branch", "source_code_folder"],
        unique=True,
    )
    op.create_table(
        "resources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("template_id", sa.UUID(), nullable=False),
        sa.Column("source_code_version_id", sa.UUID(), nullable=True),
        sa.Column("storage_id", sa.UUID(), nullable=True),
        sa.Column("storage_path", sa.String(), nullable=True),
        sa.Column("variables", sa.JSON(), nullable=False),
        sa.Column("outputs", sa.JSON(), nullable=False),
        sa.Column("dependency_tags", sa.JSON(), nullable=False),
        sa.Column("dependency_config", sa.JSON(), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("abstract", sa.Boolean(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column(
            "state",
            sa.Enum("PROVISION", "PROVISIONED", "DESTROY", "DESTROYED", name="model_state", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "IN_PROGRESS",
                "DONE",
                "ERROR",
                "UNKNOWN",
                "APPROVAL_PENDING",
                "PENDING",
                "REJECTED",
                "READY",
                "ENABLED",
                "DISABLED",
                name="model_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_code_version_id"],
            ["source_code_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["storage_id"],
            ["storages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["templates.id"],
        ),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], name="fk_resource_workspace_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_resource_name_template_id", "resources", ["name", "template_id"], unique=True)
    op.create_index(
        "ix_template_id_scv_id_name", "resources", ["template_id", "source_code_version_id", "name"], unique=True
    )
    op.create_table(
        "source_codes_output_configs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_code_version_id", sa.UUID(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["source_code_version_id"], ["source_code_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "resource_integrations",
        sa.Column("resource_id", sa.UUID(), nullable=False),
        sa.Column("integration_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["integration_id"], ["integrations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["resource_id"], ["resources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("resource_id", "integration_id"),
    )
    op.create_table(
        "resource_links",
        sa.Column("parent_id", sa.UUID(), nullable=False),
        sa.Column("child_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["resources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["resources.id"],
        ),
        sa.PrimaryKeyConstraint("parent_id", "child_id"),
    )
    op.create_table(
        "resources_temp_state",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_resources_temp_state_resource_id", "resources_temp_state", ["resource_id"], unique=True)
    op.create_table(
        "source_codes_configs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_code_version_id", sa.UUID(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("default", sa.JSON(), nullable=True),
        sa.Column("frozen", sa.Boolean(), nullable=False),
        sa.Column("unique", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("options", sa.JSON(), nullable=False),
        sa.Column("reference_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["reference_id"], ["source_codes_output_configs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_code_version_id"], ["source_code_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("source_codes_configs")
    op.drop_index("ix_resources_temp_state_resource_id", table_name="resources_temp_state")
    op.drop_table("resources_temp_state")
    op.drop_table("resource_links")
    op.drop_table("resource_integrations")
    op.drop_table("source_codes_output_configs")
    op.drop_index("ix_template_id_scv_id_name", table_name="resources")
    op.drop_index("ix_resource_name_template_id", table_name="resources")
    op.drop_table("resources")
    op.drop_index("ix_source_code_version_version_unique", table_name="source_code_versions")
    op.drop_index("ix_source_code_version_branch_unique", table_name="source_code_versions")
    op.drop_table("source_code_versions")
    op.drop_index("ix_name_integration_id", table_name="workspaces")
    op.drop_table("workspaces")
    op.drop_table("template_links")
    op.drop_table("storages")
    op.drop_index(op.f("ix_source_codes_source_code_url"), table_name="source_codes")
    op.drop_table("source_codes")
    op.drop_table("user_accounts_associations")
    op.drop_index(op.f("ix_templates_template"), table_name="templates")
    op.drop_index(op.f("ix_templates_name"), table_name="templates")
    op.drop_table("templates")
    op.drop_table("tasks")
    op.drop_index("ix_name_integration_type_integration_provider", table_name="integrations")
    op.drop_table("integrations")
    op.drop_table("feature_flags")
    op.drop_index("ix_casbin_rules_types", table_name="casbin_rules")
    op.drop_table("casbin_rules")
    op.drop_index(op.f("ix_auth_providers_name"), table_name="auth_providers")
    op.drop_index(op.f("ix_auth_providers_auth_provider"), table_name="auth_providers")
    op.drop_table("auth_providers")
    op.drop_table("audit_logs")
    op.drop_table("workers")
    op.drop_index("ix_identifier_provider", table_name="users")
    op.drop_table("users")
    op.drop_table("scheduler_jobs")
    op.drop_table("revisions")
    op.drop_index("ix_trace_id", table_name="logs")
    op.drop_index("ix_expire_at", table_name="logs", postgresql_using="btree")
    op.drop_index("ix_execution_start", table_name="logs")
    op.drop_index("ix_entity_id", table_name="logs")
    op.drop_index("ix_created_at", table_name="logs", postgresql_using="btree")
    op.drop_table("logs")
    op.drop_index(op.f("ix_caches_module"), table_name="caches")
    op.drop_index(op.f("ix_caches_key"), table_name="caches")
    op.drop_table("caches")
    # ### end Alembic commands ###
