"""change schema for workflow

Revision ID: 48a209f9d7af
Revises: 51993b54e07b
Create Date: 2026-04-01 15:42:51.184583

"""

from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "48a209f9d7af"
down_revision: str | None = "51993b54e07b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("workflows_blueprint_id_fkey"), "workflows", "blueprints", ["blueprint_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("workflows_blueprint_id_fkey"), "workflows", type_="foreignkey")
    # ### end Alembic commands ###
