"""add scv lifecycle

Revision ID: 4d73cdd3e66b
Revises: 3395f990627f
Create Date: 2026-07-30 10:50:43.866295

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4d73cdd3e66b"
down_revision: str | None = "3395f990627f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "source_code_versions",
        sa.Column(
            "lifecycle_state",
            sa.Enum(
                "PREVIEW",
                "ACTIVE",
                "DEPRECATED",
                "UNKNOWN",
                "ARCHIVED",
                name="version_lifecycle_state",
                native_enum=False,
            ),
            nullable=False,
            server_default="UNKNOWN",
        ),
    )
    op.add_column("source_code_versions", sa.Column("breaking_changes", sa.String(), nullable=True))
    op.add_column("source_code_versions", sa.Column("index", sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("source_code_versions", "index")
    op.drop_column("source_code_versions", "breaking_changes")
    op.drop_column("source_code_versions", "lifecycle_state")
    # ### end Alembic commands ###
