"""change schema

Revision ID: 51993b54e07b
Revises: 80f444d5da6b
Create Date: 2026-04-01 15:35:32.861088

"""

from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "51993b54e07b"
down_revision: str | None = "80f444d5da6b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("workflow_steps_resource_id_fkey"), "workflow_steps", type_="foreignkey")
    op.create_foreign_key(
        op.f("workflow_steps_resource_id_fkey"),
        "workflow_steps",
        "resources",
        ["resource_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("workflow_steps_resource_id_fkey"), "workflow_steps", type_="foreignkey")
    op.create_foreign_key(
        op.f("workflow_steps_resource_id_fkey"), "workflow_steps", "resources", ["resource_id"], ["id"]
    )
    # ### end Alembic commands ###
