"""add notifications

Revision ID: 54101e3a8c07
Revises: 58834976a0ba
Create Date: 2026-06-09 08:37:23.840100

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "54101e3a8c07"
down_revision: str | None = "58834976a0ba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_preferences",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(length=150), nullable=False),
        sa.Column(
            "channels",
            sa.ARRAY(sa.Enum("SLACK", "IN_APP", name="notification_channel", native_enum=False)),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("unique_user_event_preference", "notification_preferences", ["user_id", "event_type"], unique=True)
    op.create_table(
        "subscriptions",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_subscriptions_lookup", "subscriptions", ["entity_type", "entity_id"], unique=False)
    op.create_index(
        "unique_user_resource_subscription", "subscriptions", ["user_id", "entity_type", "entity_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("unique_user_resource_subscription", table_name="subscriptions")
    op.drop_index("idx_subscriptions_lookup", table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index("unique_user_event_preference", table_name="notification_preferences")
    op.drop_table("notification_preferences")
    # ### end Alembic commands ###
