"""add config template reference

Revision ID: 55a4914f255c
Revises: 38138db5d62b
Create Date: 2025-12-19 13:57:32.572359

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "55a4914f255c"
down_revision: str | None = "38138db5d62b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_config_template_references",
        sa.Column("template_id", sa.UUID(), nullable=False),
        sa.Column("reference_template_id", sa.UUID(), nullable=False),
        sa.Column("input_config_name", sa.String(), nullable=False),
        sa.Column("output_config_name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["reference_template_id"], ["templates.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["template_id"], ["templates.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint(
            "template_id", "reference_template_id", "input_config_name", "output_config_name", "id"
        ),
    )
    op.create_index(
        "ix_template_output_config_name",
        "source_config_template_references",
        ["template_id", "reference_template_id", "input_config_name"],
        unique=True,
    )
    op.drop_constraint(op.f("source_codes_configs_reference_id_fkey"), "source_codes_configs", type_="foreignkey")
    op.drop_column("source_codes_configs", "reference_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("source_codes_configs", sa.Column("reference_id", sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(
        op.f("source_codes_configs_reference_id_fkey"),
        "source_codes_configs",
        "source_codes_output_configs",
        ["reference_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index("ix_template_output_config_name", table_name="source_config_template_references")
    op.drop_table("source_config_template_references")
    # ### end Alembic commands ###
