"""worker tasks

Revision ID: 68808bd7a046
Revises: 4fa2cb8495ad
Create Date: 2026-05-19 10:32:57.834006

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "68808bd7a046"
down_revision: str | None = "4fa2cb8495ad"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workers", sa.Column("current_task", sa.JSON(), nullable=True))
    op.add_column("workers", sa.Column("tasks_completed", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workers", "tasks_completed")
    op.drop_column("workers", "current_task")
    # ### end Alembic commands ###
