"""add tool model

Revision ID: 69f0743c5399
Revises: b7e41c9d2f08
Create Date: 2026-09-25 00:14:43.860978

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "69f0743c5399"
down_revision: str | None = "b7e41c9d2f08"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tools",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("os", sa.String(), nullable=False),
        sa.Column("arch", sa.String(), nullable=False),
        sa.Column("executable", sa.String(), nullable=False),
        sa.Column("source_url", sa.String(), nullable=False),
        sa.Column("sha256", sa.String(), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "IN_PROGRESS",
                "DONE",
                "ERROR",
                "CANCELLED",
                "UNKNOWN",
                "APPROVAL_PENDING",
                "PENDING",
                "REJECTED",
                "READY",
                "ENABLED",
                "DISABLED",
                name="model_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("error_message", sa.String(), nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version", "os", "arch", name="uq_tools_name_version_os_arch"),
    )
    op.create_index(op.f("ix_tools_name"), "tools", ["name"], unique=False)
    op.create_index("uq_tools_is_default", "tools", ["is_default"], unique=True, postgresql_where=sa.text("is_default"))
    op.add_column("executors", sa.Column("tool_id", sa.UUID(), nullable=True))
    op.create_foreign_key("fk_executors_tool_id", "executors", "tools", ["tool_id"], ["id"], ondelete="RESTRICT")
    op.add_column("resources", sa.Column("tool_id", sa.UUID(), nullable=True))
    op.create_foreign_key("fk_resources_tool_id", "resources", "tools", ["tool_id"], ["id"], ondelete="RESTRICT")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_resources_tool_id", "resources", type_="foreignkey")
    op.drop_column("resources", "tool_id")
    op.drop_constraint("fk_executors_tool_id", "executors", type_="foreignkey")
    op.drop_column("executors", "tool_id")
    op.drop_index("uq_tools_is_default", table_name="tools", postgresql_where=sa.text("is_default"))
    op.drop_index(op.f("ix_tools_name"), table_name="tools")
    op.drop_table("tools")
    # ### end Alembic commands ###
