"""change logs and audit schema

Revision ID: 6a3ed2c3aa2b
Revises: a94fd5a63385
Create Date: 2026-04-15 13:06:25.325251

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6a3ed2c3aa2b"
down_revision: str | None = "a94fd5a63385"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("audit_logs", sa.Column("revision_number", sa.Integer(), nullable=True))
    op.add_column("logs", sa.Column("audit_log_id", sa.UUID(), nullable=True))
    op.execute(
        "UPDATE logs SET trace_id = NULL WHERE trace_id IS NOT NULL AND trace_id !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'"  # noqa: E501
    )
    op.alter_column(
        "logs",
        "trace_id",
        existing_type=sa.VARCHAR(),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="trace_id::uuid",
    )
    op.create_index("ix_audit_log_id", "logs", ["audit_log_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_audit_log_id", table_name="logs")
    op.alter_column("logs", "trace_id", existing_type=sa.UUID(), type_=sa.VARCHAR(), existing_nullable=True)
    op.drop_column("logs", "audit_log_id")
    op.drop_column("audit_logs", "revision_number")
    # ### end Alembic commands ###
