"""add_source_code_commits

Revision ID: 73eab5aee8af
Revises: 3890388593d8
Create Date: 2026-10-09 12:27:27.252318

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "73eab5aee8af"
down_revision: str | None = "3890388593d8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_code_commits",
        sa.Column("source_code_id", sa.UUID(), nullable=False),
        sa.Column("branch", sa.String(), nullable=False),
        sa.Column("sha", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("author_name", sa.String(), nullable=False),
        sa.Column("author_email", sa.String(), nullable=False),
        sa.Column("authored_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_code_id"], ["source_codes.id"], name="fk_source_code_commit_source_code_id", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_source_code_commit_source_code_id_branch_position",
        "source_code_commits",
        ["source_code_id", "branch", "position"],
        unique=False,
    )
    op.create_index(
        "ix_source_code_commit_source_code_id_branch_sha",
        "source_code_commits",
        ["source_code_id", "branch", "sha"],
        unique=True,
    )
    op.add_column("source_codes", sa.Column("default_branch", sa.String(), nullable=True))
    op.add_column("source_codes", sa.Column("git_tag_shas", sa.JSON(none_as_null=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("source_codes", "git_tag_shas")
    op.drop_column("source_codes", "default_branch")
    op.drop_index("ix_source_code_commit_source_code_id_branch_sha", table_name="source_code_commits")
    op.drop_index("ix_source_code_commit_source_code_id_branch_position", table_name="source_code_commits")
    op.drop_table("source_code_commits")
    # ### end Alembic commands ###
