"""add audit log entity snapshot

Revision ID: 7818f3caeb01
Revises: 2612e39a8694
Create Date: 2026-09-30 13:42:17.381247

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7818f3caeb01"
down_revision: str | None = "2612e39a8694"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("audit_logs", sa.Column("entity_snapshot", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("audit_logs", "entity_snapshot")
    # ### end Alembic commands ###
