"""add entity cron

Revision ID: 7c943fcdd9c7
Revises: b7e41c9d2f08
Create Date: 2026-09-29 09:59:26.971113

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7c943fcdd9c7"
down_revision: str | None = "b7e41c9d2f08"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("cron", sa.String(), nullable=True))
    op.add_column("tasks", sa.Column("timezone", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "timezone")
    op.drop_column("tasks", "cron")
    # ### end Alembic commands ###
