"""change logs and audit schema

Revision ID: 8a4038807e71
Revises: a94fd5a63385
Create Date: 2026-04-14 17:22:49.000076

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a4038807e71"
down_revision: str | None = "a94fd5a63385"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("audit_logs", sa.Column("revision_number", sa.Integer(), nullable=True))
    op.add_column("logs", sa.Column("audit_log_id", sa.UUID(), nullable=True))
    op.create_index("ix_audit_log_id", "logs", ["audit_log_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_audit_log_id", table_name="logs")
    op.drop_column("logs", "audit_log_id")
    op.drop_column("audit_logs", "revision_number")
    # ### end Alembic commands ###
