"""template configuration

Revision ID: a94fd5a63385
Revises: 2a21f0adafc4
Create Date: 2026-03-02 13:19:52.422293

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a94fd5a63385"
down_revision: str | None = "2a21f0adafc4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("templates", sa.Column("configuration", sa.JSON(), nullable=False, server_default="{}"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("templates", "configuration")
    # ### end Alembic commands ###
