"""add resource scheduler

Revision ID: ee182a56460b
Revises: 4d73cdd3e66b
Create Date: 2026-08-18 13:51:38.456128

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ee182a56460b"
down_revision: str | None = "4d73cdd3e66b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "action",
            sa.Enum(
                "CREATE",
                "UPDATE",
                "EDIT",
                "DESTROY",
                "DELETE",
                "REJECT",
                "APPROVE",
                "EXECUTE",
                "RETRY",
                "RECREATE",
                "SYNC",
                "DRYRUN",
                "DRYRUN_WITH_TEMP_STATE",
                "DISABLE",
                "ENABLE",
                "DOWNLOAD",
                "CASCADE_DESTROY",
                name="model_actions",
                native_enum=False,
            ),
            nullable=True,
        ),
    )
    op.add_column("tasks", sa.Column("run_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("tasks", sa.Column("error", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "error")
    op.drop_column("tasks", "run_at")
    op.drop_column("tasks", "action")
    # ### end Alembic commands ###
