"""add storage id

Revision ID: f323032ca48e
Revises: d4d7e73ae19b
Create Date: 2026-03-16 13:20:25.882096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f323032ca48e'
down_revision: Union[str, None] = 'd4d7e73ae19b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_steps', sa.Column('storage_id', sa.UUID(), nullable=True))
    op.add_column('workflows', sa.Column('storage_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'storage_id')
    op.drop_column('workflow_steps', 'storage_id')
    # ### end Alembic commands ###
