"""add executors

Revision ID: f6486f2ec823
Revises: 55a4914f255c
Create Date: 2026-01-28 14:39:40.226656

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f6486f2ec823"
down_revision: str | None = "55a4914f255c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "executors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("runtime", sa.Enum("opentofu", native_enum=False), nullable=False),
        sa.Column("command_args", sa.String(), nullable=False),
        sa.Column("source_code_id", sa.UUID(), nullable=False),
        sa.Column("source_code_version", sa.String(), nullable=True),
        sa.Column("source_code_branch", sa.String(), nullable=True),
        sa.Column("source_code_folder", sa.String(), nullable=False),
        sa.Column("storage_id", sa.UUID(), nullable=True),
        sa.Column("storage_path", sa.String(), nullable=True),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column(
            "state",
            sa.Enum("PROVISION", "PROVISIONED", "DESTROY", "DESTROYED", name="model_state", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "IN_PROGRESS",
                "DONE",
                "ERROR",
                "UNKNOWN",
                "APPROVAL_PENDING",
                "PENDING",
                "REJECTED",
                "READY",
                "ENABLED",
                "DISABLED",
                name="model_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["source_code_id"], ["source_codes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["storage_id"],
            ["storages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_executors_name"), "executors", ["name"], unique=True)
    op.create_table(
        "executor_integrations",
        sa.Column("executor_id", sa.UUID(), nullable=False),
        sa.Column("integration_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["executor_id"], ["executors.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["integration_id"], ["integrations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("executor_id", "integration_id"),
    )
    op.create_table(
        "executor_secrets",
        sa.Column("executor_id", sa.UUID(), nullable=False),
        sa.Column("secret_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["executor_id"], ["executors.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["secret_id"], ["secrets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("executor_id", "secret_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("executor_secrets")
    op.drop_table("executor_integrations")
    op.drop_index(op.f("ix_executors_name"), table_name="executors")
    op.drop_table("executors")
    # ### end Alembic commands ###
