import {
  AwsIcon,
  AzureLogoIcon,
  BitbucketIcon,
  DatadogIcon,
  GithubIcon,
  GitLabIcon,
  GoogleCloudIcon,
  MongoDBIcon,
} from "../icons/Icons";

import { ConnectionType, IntegrationType, Provider } from "./types";

export const providers: Provider[] = [
  {
    type: IntegrationType.GIT,
    connectionType: ConnectionType.TOKEN,
    name: "Bitbucket",
    icon: BitbucketIcon,
    slug: "bitbucket",
    instructions: [
      "Go to <a href='https://id.atlassian.com/manage-profile/security/api-tokens' target='_blank'><strong>Bitbucket API Tokens</strong></a> and click <strong>Create API token</strong>",
      "Select 'Create API token with scopes'",
      "Set an appropriate expiration date",
      "Select API token APP -> Bitbucket",
      "Select scopes based on your needs. At a minimum, select the following scopes: <pre> read:project:bitbucket \n read:pullrequest:bitbucket\n read:repository:bitbucket\n read:user:bitbucket \n read:workspace:bitbucket\n write:pullrequest:bitbucket \n write:repository:bitbucket</pre>",
      "Copy the generated token and paste it below",
    ],
    tokenLink: "",
  },
  {
    type: IntegrationType.GIT,
    connectionType: ConnectionType.SSH,
    name: "Bitbucket SSH",
    icon: BitbucketIcon,
    slug: "bitbucket",
    instructions: [
      "Generate a new SSH key pair on your local machine using the command: ssh-keygen -t rsa -b 4096",
      "Add the public key to your Bitbucket account by going to Personal settings → SSH keys → Add key",
      "Copy the contents of your private key file (usually located at ~/.ssh/id_rsa) and paste it below",
    ],
    tokenLink: "",
  },
  {
    type: IntegrationType.GIT,
    connectionType: ConnectionType.TOKEN,
    name: "GitHub",
    icon: GithubIcon,
    slug: "github",
    instructions: [
      'Go to <a href="https://github.com/settings/personal-access-tokens" target="_blank"><strong>GitHub Personal Access Tokens</strong></a> and click <strong>Generate new token</strong>',
      "Give your token a descriptive name (e.g., 'InfraKitchen Integration')",
      "Set an appropriate expiration date",
      "Under <strong>Repository access</strong>, select the repositories based on your needs",
      "Under <strong>Repository permissions</strong>, grant <strong>Contents: Read</strong> and <strong>Metadata: Read</strong> (required for accessing private repositories)",
      "If you need to create pull requests, also grant <strong>Pull requests: Write</strong>",
      "Click <strong>Generate token</strong>",
      "Copy the generated token and paste it below",
    ],
    tokenLink: "",
  },
  {
    type: IntegrationType.GIT,
    connectionType: ConnectionType.SSH,
    name: "GitHub SSH",
    icon: GithubIcon,
    slug: "github",
    instructions: [
      "Generate a new SSH key pair on your local machine using the command: ssh-keygen -t rsa -b 4096",
      "Add the public key to your GitHub account by going to Settings → SSH and GPG keys → New SSH key",
      "Copy the contents of your private key file (usually located at ~/.ssh/id_rsa) and paste it below",
    ],
    tokenLink: "",
  },
  {
    type: IntegrationType.GIT,
    connectionType: ConnectionType.TOKEN,
    name: "GitLab",
    icon: GitLabIcon,
    slug: "gitlab",
    instructions: [
      'Go to <a href="https://gitlab.com/-/user_settings/personal_access_tokens" target="_blank"><strong>GitLab</strong></a> or your own instance URL and either',
      'create a <strong>personal access token</strong>, a <strong>group access token</strong> or a <strong>project access token</strong>',
      "Give your token a descriptive name (e.g., 'InfraKitchen Integration')",
      "Set an appropriate expiration date",
      "Under <strong>Select a role</strong>, select the access level based on your needs",
      "Under <strong>Select scopes</strong>, grant <strong>read_api</strong> and <strong>read_repository</strong> (required for accessing private repositories)",
      "If you need to create pull requests, then grant <strong>api</strong> and <strong>write_repository</strong> instead",
      "Click <strong>Create token</strong>",
      "Copy the generated token and paste it below",
    ],
    tokenLink: "",
  },
  {
    type: IntegrationType.GIT,
    connectionType: ConnectionType.TOKEN,
    name: "Azure Repos",
    icon: AzureLogoIcon,
    slug: "azure_devops",
    instructions: [
      "Go to User settings → Personal access tokens → New Token in your Azure DevOps account",
      "Give your token a descriptive name (e.g., 'InfraKitchen Integration')",
      "Set an appropriate expiration date",
      "Under <strong>Scopes</strong>, select <strong>Custom defined</strong>",
      "Select the following scopes based on your needs: <pre> Code (Read, write & manage)</pre>",
      "Click <strong>Create</strong>",
      "Copy the generated token and paste it below",
    ],
    tokenLink: "",
  },
  {
    type: IntegrationType.GIT,
    connectionType: ConnectionType.SSH,
    name: "Azure Repos SSH",
    icon: AzureLogoIcon,
    slug: "azure_devops",
    instructions: [
      "Generate a new SSH key pair on your local machine using the command: ssh-keygen -t rsa -b 4096",
      "Add the public key to your Azure DevOps account by going to User settings → SSH Public Keys → Add",
      "Copy the contents of your private key file (usually located at ~/.ssh/id_rsa) and paste it below",
    ],
    tokenLink: "",
  },
  {
    type: IntegrationType.CLOUD,
    name: "AWS",
    icon: AwsIcon,
    slug: "aws",
    instructions: [
      "Log in to the <strong>AWS Console</strong> and navigate to the <strong>IAM service</strong>",
      "Create a new <strong>IAM user</strong> or select an existing one for this integration",
      "Attach appropriate <strong>AWS managed policies</strong> or define <strong>custom policies</strong> based on the AWS infrastructure you want InfraKitchen to manage",
      "Generate an <strong>Access Key</strong> for the IAM user",
      "<i>Optional - For enhanced security using role assumption:</i>",
      "Create an <strong>IAM role</strong> with the necessary permissions instead of attaching policies directly to the IAM user",
      "In the role's <strong>trust policy</strong>, allow the IAM user to assume this role",
      "Attach the <code>sts:AssumeRole</code> permission to the IAM user for this specific role",
      "Provide the <strong>AWS Account ID</strong>, <strong>Access Key ID</strong>, <strong>Secret Access Key</strong>, and <strong>Role Name</strong> (optional) in the configuration below",
    ],
    tokenLink: "",
  },
  {
    type: IntegrationType.CLOUD,
    name: "Azure",
    icon: AzureLogoIcon,
    slug: "azurerm",
    instructions: [
      "Log in to the <strong>Azure Portal</strong> and navigate to the <strong>Azure Active Directory</strong> service",
      "Create a new <strong>App Registration</strong> for this integration",
      "Note down the <strong>Application (client) ID</strong> and <strong>Directory (tenant) ID</strong>",
      "Navigate to <strong>Certificates & secrets</strong> and create a new <strong>Client Secret</strong>. Note down the secret value as it will be shown only once",
      "Assign appropriate <strong>roles</strong> to the App Registration at the subscription or resource group level based on the Azure resources you want InfraKitchen to manage",
      "Provide the <strong>Client ID</strong>, <strong>Client Secret</strong>, and <strong>Tenant ID</strong> in the configuration below",
    ],
    tokenLink: "",
  },
  {
    type: IntegrationType.CLOUD,
    name: "Google Cloud",
    icon: GoogleCloudIcon,
    slug: "gcp",
    instructions: [],
    tokenLink: "",
  },
  {
    type: IntegrationType.CLOUD,
    name: "MongoDB Atlas",
    icon: MongoDBIcon,
    slug: "mongodb_atlas",
    instructions: [],
    tokenLink: "",
  },
  {
    type: IntegrationType.CLOUD,
    name: "Datadog",
    icon: DatadogIcon,
    slug: "datadog",
    instructions: [],
    tokenLink: "",
  },
];
