name: Build and Deploy Packages to NPM manually

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-publish-to-npm:
    runs-on: ubuntu-latest

    steps:
      #############################################################################
      # common steps
      #############################################################################
      - uses: actions/checkout@v7.0.0

      - name: use node.js 24.x
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "24.x"
          registry-url: https://registry.npmjs.org/ # Needed for auth
          cache: pnpm
          cache-dependency-path: ui/pnpm-lock.yaml

      - name: Enable pnpm
        run: corepack enable

      - name: Run ESLint
        run: ./scripts/check_typescript.sh

      #############################################################################
      # publish a library to npm
      #############################################################################
      - name: Setup version based on branch
        working-directory: ./ui/frontend-lib
        run: |
          VERSION=$(npm pkg get version --workspaces=false | tr -d \")
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            npm pkg set version=$VERSION
          else
            npm pkg set version=$VERSION-$(date +%F%T | tr -d '\-:')-$(echo ${{ github.sha }} | cut -c 1-7)
          fi

      #############################################################################
      # publish a release to npm
      #############################################################################
      - name: publish package
        run: |
          cd ui
          pnpm install --frozen-lockfile
          pnpm --filter @electrolux-oss/infrakitchen build
          cd frontend-lib

          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            pnpm publish --access public --no-git-checks
          else
            pnpm publish --access public --no-git-checks --tag rc
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
